import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { Toaster } from 'react-hot-toast';

import Navbar from './components/Navbar/Navbar';
// import ClientOnly from './components/ClientOnly';
import LoginModal from './components/Modals/LoginModal';
import Footer from './components/Footer';
import useUserState from './hooks/useUserState';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Toaster />
        <Navbar />
        <LoginModal />
         <div className='min-h-screen'> 
        {children}
         </div>
        <Footer />
        </body>
    </html>
  )
}
